// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFyvj2xo0Babl1zbfDSjN2NLnGYdTDTi0',
    appId: '1:391410452371:web:123e0fa6a0aea63c318a66',
    messagingSenderId: '391410452371',
    projectId: 'studio-2504054971-f332e',
    authDomain: 'studio-2504054971-f332e.firebaseapp.com',
    storageBucket: 'studio-2504054971-f332e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWErX68cypQu-C5CH3_WErptK133h0XPo',
    appId: '1:391410452371:android:c287c6af8e06fd12318a66',
    messagingSenderId: '391410452371',
    projectId: 'studio-2504054971-f332e',
    storageBucket: 'studio-2504054971-f332e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWE1TZ4vB6EWIsfGV037MKzxoD2ugXmQ8',
    appId: '1:391410452371:ios:36a89d5a5b8baf91318a66',
    messagingSenderId: '391410452371',
    projectId: 'studio-2504054971-f332e',
    storageBucket: 'studio-2504054971-f332e.firebasestorage.app',
    iosBundleId: 'com.example.airQualityFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWE1TZ4vB6EWIsfGV037MKzxoD2ugXmQ8',
    appId: '1:391410452371:ios:36a89d5a5b8baf91318a66',
    messagingSenderId: '391410452371',
    projectId: 'studio-2504054971-f332e',
    storageBucket: 'studio-2504054971-f332e.firebasestorage.app',
    iosBundleId: 'com.example.airQualityFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFyvj2xo0Babl1zbfDSjN2NLnGYdTDTi0',
    appId: '1:391410452371:web:4a7606eb53118cf8318a66',
    messagingSenderId: '391410452371',
    projectId: 'studio-2504054971-f332e',
    authDomain: 'studio-2504054971-f332e.firebaseapp.com',
    storageBucket: 'studio-2504054971-f332e.firebasestorage.app',
  );
}
